denoland/docs

deploy/manual/index.mdx

Fix hello world serve example

---

runtime/manual/node/npm_specifiers.md

Revert changes from denoland/manual#689 at the request of the author.

revert changes from denoland/manual#689

---

LICENSE
README.md
runtime/manual/node/npm_specifiers.md

This reverts commit 6616602417ba83642cbc06f1d3df3590570bc9bf.

Revert "revert changes from denoland/manual#689 (#116)"

---

.github/workflows/update_versions.ts
.github/workflows/update_versions.yml

ci: add update_versions workflow

---

runtime/manual/tools/jupyter.md

Documentation from providing support in https://github.com/denoland/deno/issues/20600
cc @guy-borderless

Include more VS Code instructions in jupyter.md

---

kv/manual/key_space.mdx

Close https://github.com/denoland/deno-docs/issues/76 
Update key_space.mdx

fix: Changed -NaN to NaN 

---

runtime/manual/basics/env_variables.md

fix(env): add special environment variables section

---

runtime/manual/references/contributing/style_guide.md

fix(style-guide): update exported function interface to match current api design

---

runtime/manual/index.mdx

This PR fixes a typo in index.mdx

fix typo moudles -> modules

---

runtime/manual/node/how_to_with_npm/react.md
runtime/tutorials/how_to_with_npm/react.md

URL description and image are different.
Format the code by the way.

fix: url description for image of react.md

---

runtime/manual/tools/task_runner.md

deno task - add 'head' command

---

runtime/manual/basics/testing/coverage.md

closes https://github.com/denoland/deno-docs/issues/226

Add `--html` option example

---

runtime/manual/references/contributing/style_guide.md

see: https://github.com/denoland/deno_std/issues/3754

docs: unified test names

---

runtime/manual/advanced/publishing/index.md

docs: including version numbers in code and content

---

babel.config.js
kv/manual/index.mdx
kv/manual/operations.mdx
runtime/manual/node/how_to_with_npm/express.md
runtime/manual/node/how_to_with_npm/vue.md
runtime/manual/tools/jupyter.md
runtime/manual/tools/script_installer.md
runtime/tutorials/file_server.md
runtime/tutorials/how_to_with_npm/prisma.md
src/theme/DocBreadcrumbs/Items/Home/index.js
src/theme/DocBreadcrumbs/index.js
src/theme/DocPage/Layout/Main/index.js
src/theme/Layout/Provider/index.js
src/theme/Layout/index.js
src/theme/Navbar/Content/index.js
src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
src/theme/Navbar/MobileSidebar/index.js
src/theme/Navbar/index.js
static/openapi.json

i kind of copied code from our API reference (https://deno.land/api@v1.38.5?unstable=&s=Deno.Kv&p=prototype.watch) so feel free to zhuzh it up so it matches the level of technical fidelity of the surrounding documentation.

add kv watch

---

runtime/manual/tools/compiler.md
static/examples/welcome.ts

Add a script hosted on the docs site for this example.

fix compile example

---

runtime/manual/basics/testing/index.md

Fixes #239 - remove unnecessary heading

remove spurrious header

---

runtime/manual/tools/unstable_flags.md

This adds in the rest of the undocumented unstable flags. We did not have reference content available for some of them, so I marked them as such. @bartlomieju if you happen to know some tidbits about these flags off the top of your head, would love some additional guidance!

add full list of flags

---

runtime/manual/node/compatibility.mdx
runtime/manual/node/migrate.md

Closes https://github.com/denoland/deno-docs/issues/156
Refs https://github.com/denoland/deno/issues/20784

Answer to `__dirname` question

---

runtime/manual/node/compatibility.mdx
runtime/manual/node/migrate.md
sidebars/runtime.js

clean up direction around __filename and __dirname

---

deploy/tutorials/tutorial-http-server.md

update simple http server example

---

kv/manual/key_expiration.mdx

add TTL to title and text body for much SEO (wow)

---

src/pages/index.jsx

That dinosaur looks lots better on a black background.

Let's put that dino in an ellipse

---

runtime/manual/tools/linter.md

Update doc for PR https://github.com/denoland/deno_lint/pull/1229
1. https://github.com/denoland/deno_lint/issues/1076
2. https://github.com/denoland/deno_lint/pull/1229
---
cc @bartlomieju

Specify reasons for ignore directives

---

deploy/tutorials/tutorial-wordpress-frontend.md

These caught my eye while browsing the docs. Thanks for your work!
ref: https://developer.wordpress.org/reference/functions/capital_p_dangit/

Fix the lowercased "p" for "WordPress" in a few places

---

docusaurus.config.js
runtime/manual/advanced/migrate_deprecations.md
runtime/tutorials/migrate_deprecations.md
sidebars/runtime.js

Add massaged version of WIP migration guide

Deprecation guide

---

runtime/manual/advanced/migrate_deprecations.md

Further work on top of #299. Apologies for the noisy diff - it's due to the re-sorting of sections in alphabetical order of their headings.

add more APIs to deprecation guide

---

runtime/manual/advanced/migrate_deprecations.md

Towards #297
Depends on https://github.com/denoland/deno/issues/22178

docs: add `Deno.funlock[Sync]()` and `Deno.flock[Sync]()` migration guides

---

runtime/manual/advanced/migrate_deprecations.md

Towards #297
PTAL @bartlomieju

docs: add `Deno.TcpConnect.rid` migration guide

---

deploy/manual/subhosting/index.md

broken links under some circumstances without trailing slashes

fix routing issues on subhosting

---

runtime/manual/tools/benchmarker.md
runtime/manual/tools/compiler.md
runtime/manual/tools/dependency_inspector.md
runtime/manual/tools/documentation_generator.md
runtime/manual/tools/formatter.md
runtime/manual/tools/init.md
runtime/manual/tools/linter.md
runtime/manual/tools/repl.md
runtime/manual/tools/script_installer.md
runtime/manual/tools/task_runner.md
runtime/manual/tools/vendor.md

fixes https://github.com/denoland/deno-docs/issues/307

change h1 for tools to include tool name

---

deploy/manual/ci_github.md
deploy/tutorials/vite.md

update to remove images reflecting old onboarding flow

---

runtime/manual/getting_started/configuration_file.md
runtime/manual/getting_started/index.md

add deno.json to title of config file section

---

src/pages/index.jsx

fix: wrong queues link on index page

---

runtime/tutorials/os_signals.md

closes https://github.com/denoland/deno_std/issues/4389

Remove example which depends on the removed std/signal

---

runtime/manual/advanced/migrate_deprecations.md

docs: `Deno.ConnectTlsOptions.certChain` migration guide

---

runtime/manual/basics/connecting_to_databases.md

Add `deno-drivers` to database docs

---

runtime/manual/tools/cache.md
runtime/manual/tools/index.md

deno cache 

---

package-lock.json
package.json

Should address security issues in the webpack dev server

bump dependencies for security vulnerability

---

deploy/tutorials/tutorial-faunadb.md

This tutorial could really do with and entire rewrite

update fauna db tutorial to use new deno deploy flow. 

---

runtime/manual/advanced/typescript/overview.md

relates to https://github.com/denoland/deno/issues/5088

add documentation for `--ext`

---

runtime/manual/getting_started/command_line_interface.md

Supports providing patterns and also works with any sub command that supports `--watch`.

Update `--watch-exclude` docs for latest changes

---

runtime/manual/advanced/migrate_deprecations.md

docs: use JSR in example code snippets

---

deploy/tutorials/tutorial-dynamodb.md

(requires jsr update once sift is on jsr)

update dynamodb tutorial to use new deploy flow and new aws ui 

---

sidebars/subhosting.js
subhosting/manual/events.md

Resolves https://github.com/denoland/deploy/issues/7405
Preview: https://deno-docs--doc-subhosting-events.deno.dev/subhosting/manual/events

Chore: document subhosting events

---

runtime/manual/getting_started/installation.md

[vfox](https://github.com/version-fox/vfox) is a cross-platform version manager, extendable via plugins.

Add vfox instructions in installation.md

---

.github/workflows/deploy.yml
docusaurus.config.js
package-lock.json
package.json
src/css/custom.css

Reverts denoland/deno-docs#412
Due to CI failure, seemingly on orama's side

Revert "feat: move search to Orama Cloud"

---

_includes/doc.tsx

fix: adjust width of manual navigation

---

runtime/manual/advanced/typescript/configuration.md

fix: remove hardcoded html from markdown table

---

runtime/manual/advanced/private_repositories.md

Fixes the image paths on https://docs.deno.com/runtime/manual/advanced/private_repositories/

Fix image paths

---

styles.css

Restyled these blocks to stand out a bit more and feel more unique between each admonition type

Restyle admonition blocks

---

_config.ts

Fix invalid images in kv pages

---

_config.ts

fix tutorials image for webhook

---

_config.ts

Allows diffs to be syntax-highlighted:

Add Prism diff support

---

runtime/manual/basics/env_variables.md
runtime/manual/basics/standard_library.md
runtime/manual/getting_started/configuration_file.md
runtime/manual/getting_started/first_steps.md
runtime/manual/index.md

Read through "Quick Start" and "Deno Basics" and mostly updated examples to use JSR. The "Connecting to databases" section still needs to be updated.

Updating JSR and other nits as I re-read docs

---

reference_gen/deno-categories.json

Fix jupyter category link in categories definition

---

reference.page.jsx
reference_gen/deno-categories.json

Fixes https://github.com/denoland/docs/issues/539
Also fixes some incorrect links

fix(reference): improve HTML titles

---

runtime/manual/advanced/jsx_dom/deno_dom.md

Fixes https://github.com/denoland/docs/issues/654

fix(deno_dom): point to JSR isntead of deno.land

---

_config.ts
by-example/dependency-management.ts
by-example/import-export.ts
examples.page.tsx
runtime/manual/basics/modules/reloading_modules.md

updating by-example examples to use a hosted version of the file instead of github raw to make urls a bit prettier

Exampleurls

---

_components/Header.tsx
_includes/doc.tsx
_includes/layout.tsx
examples.page.tsx
index.page.tsx

- Implements a "skip to content" link for better keyboard accessibility
- Minor semantic improvements

Implement skip link

---

runtime/manual/basics/modules/integrity_checking.md

Mostly copies the example given in the blog post.
Addresses https://github.com/denoland/deno/pull/25214#pullrequestreview-2261092735

docs: add "Freezing the lockfile" section

---

runtime/fundamentals/testing.md

closes https://github.com/denoland/website_feedback/issues/80

fix: bdd testing example

---

runtime/manual/basics/modules/index.md

docs: fix 404 link

---

runtime/fundamentals/testing.md
runtime/fundamentals/web_dev.md
runtime/index.md
runtime/manual/basics/modules/index.md
runtime/tutorials/index.md

Fixes some more 404 links that popped up over night in our logs.

fix: more 404 links

---

deno.json
deno.lock

Upgrades lume which includes fixes related to serve mode.

chore: upgrade lume

---

runtime/fundamentals/testing.md

Hello deno document maintainer.
I evaluated this sample with deno repl. This sample should add URL `jsr' scheme.

Need to add URL with scheme

---

runtime/reference/cli/formatter.md

https://docs.deno.com/runtime/reference/cli/formatter/#configuration

fix: Broken link (configuration)

---

_components/Sidebar.tsx
deploy/api/dynamic-import.md
deploy/kv/manual/data_modeling_typescript.md
deploy/kv/manual/operations.md
examples/reading-files.ts
reference_gen/node-docs.ts
runtime/fundamentals/configuration.md

Done using [`typos`](https://github.com/crate-ci/typos).

docs: fix typos

---

styles.css
tabs.client.ts

Changes filename bar color to be something that doesn't contrast with the rest of the box as much and fixes a bug where sometimes a page would load without an active tab state being set.

fix hidden tab bug and change filename bar colors

---

runtime/reference/cli/formatter.md

Closes https://github.com/denoland/docs/issues/869

Update formatter page

---

runtime/getting_started/command_line_interface.md
runtime/reference/cli/cache.md
runtime/reference/cli/check.md
runtime/reference/cli/eval.md
runtime/reference/cli/test.md
runtime/reference/continuous_integration.md

Closes https://github.com/denoland/docs/issues/874

Remove --lock-write references

---

examples/http-requests.ts

Add JSON body example to http-requests.ts

---

runtime/tutorials/os_signals.md

Correct typo in os_signals.md

---

runtime/reference/deno_namespace_apis.md

Closes https://github.com/denoland/docs/issues/897

Remove unneeded info from 'Deno namespace APIs'

---

runtime/tutorials/how_to_with_npm/react.md
runtime/tutorials/how_to_with_npm/vue.md

updating react tutorial to not use create-vite-extra 

---

runtime/reference/cli/compiler.md

Closes https://github.com/denoland/docs/issues/675

Update deno compile docs

---

runtime/fundamentals/node.md
runtime/reference/cli/install.md

Closes https://github.com/denoland/docs/issues/909
Closes https://github.com/denoland/docs/issues/908

Node-API addons

---

runtime/_data.ts
runtime/fundamentals/stability_and_releases.md
runtime/reference/migrate_deprecations.md
runtime/reference/migration_guide.md
runtime/reference/private_repositories.md

Closes https://github.com/denoland/docs/issues/836

Migration guide copy

---

runtime/_data.ts
runtime/fundamentals/debugging.md
runtime/fundamentals/linting_and_formatting.md
runtime/fundamentals/web_dev.md
runtime/fundamentals/workspaces.md
runtime/getting_started/command_line_interface.md
runtime/getting_started/setup_your_environment.md
runtime/help.md
runtime/reference/continuous_integration.md
runtime/reference/private_repositories.md
runtime/tutorials/digital_ocean.md
runtime/tutorials/fetch_data.md
runtime/tutorials/file_server.md
runtime/tutorials/file_system_events.md
runtime/tutorials/google_cloud_run.md
runtime/tutorials/hashbang.md
runtime/tutorials/how_to_with_npm/mongoose.md
runtime/tutorials/how_to_with_npm/redis.md
runtime/tutorials/index.md
runtime/tutorials/kinsta.md
runtime/tutorials/module_metadata.md
runtime/tutorials/os_signals.md
runtime/tutorials/subprocess.md
runtime/tutorials/word_finder.md

Updating title casing of files across entire of docs
Updating tutorials index page to match what is now in the sidebar

Minor fixes

---

runtime/fundamentals/node.md

Closes https://github.com/denoland/docs/issues/936

Add CTA box linking to Node API reference

---

runtime/reference/ts_config_migration.md

These values have been changed in https://github.com/denoland/deno/pull/25695 and https://github.com/denoland/deno/pull/25465

Update default values of `noImplicitOverride` and `useUnknownInCatchVariables`

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/update_versions.yml
deploy/manual/ci_github.md
runtime/fundamentals/linting_and_formatting.md
runtime/reference/continuous_integration.md

Revert "feat: update setup-deno"

---

runtime/fundamentals/node.md

Fixes https://github.com/denoland/docs/issues/882

updating node modules support

---

runtime/tutorials/google_cloud_run.md

typo, fixes #162

---

runtime/contributing/building_from_source.md

Update LLVM version in building_from_source.md

---

runtime/tutorials/how_to_with_npm/next.md

Simple spelling mistake on tutorial

Fix spelling mistake on next.md

---

deploy/manual/deployctl.md

Fixes https://github.com/denoland/deploy_feedback/issues/730

fix: Add `-g` option to deployctl install instruction

---

examples/exponential-backoff.ts

This pull request adds a new example demonstrating the implementation of exponential backoff using the `retry` utility from the `@std/async` library. The example includes detailed comments and configuration for retry options.

docs: Exponential backoff example

---

examples/aes-encryption.ts

Simple example showing how to use AES encryption/decryption in deno

AES Encryption and Decryption Example

---

examples/streaming-files.ts

Replace `do...while` with `while(true)`

Update streaming-files.ts with a simplified loop

---

runtime/tutorials/how_to_with_npm/next.md

Trying to follow along and wasn't sure where context is even used when following the tutorial from scratch.

Update docs to remove unused context

---

examples/unzip-gzipped-file.ts

Added an example showing how to use Deno to read in a gzipped file and write its output to a newly created file.
This was asked for by #1137

add example on how to unzip a gzipped file

---

deploy/manual/environment-variables.md
runtime/reference/env_variables.md

This PR is in relation with [this PR](https://github.com/denoland/deno/pull/26527) that updates the required document with the required information.

docs(runtime): update --env-flag arg flag to include multiple file support

---

examples/reading-system-metrics.ts

Expanded system metrics with memory usage.

docs: Expand system metrics example

---

runtime/tutorials/how_to_with_npm/next.md

- Added a step to install dependencies using `deno install` before starting the Next.js app with `deno task dev`.
- Improves clarity and ensures all necessary steps are included in the setup process.

Update Next.js app setup instructions with Deno

---

examples/hmac-generate-verify.ts

Simple example showing how to generate and verify HMAC, which is very common way of ensuring that no data has been tempered when two parties transact/exchange data.

Cryptography example demonstrating generation and verification of HMAC

---

runtime/reference/cli/jupyter.md

Ref https://github.com/denoland/deno/pull/26284

Add `Deno.jupyter.image` API docs

---

deno.json
deno.lock
reference.page.jsx

Fixes https://github.com/denoland/docs/issues/1161

replace encoded slash character in page titles

---

runtime/reference/migration_guide.md

Typo in `migration_guide.md`

---

_components/Breadcrumbs.tsx
_components/HeaderAnchor.tsx
_components/NavigationButton.tsx
_components/TableOfContentsItem.tsx
_components/TableOfContentsItemMobile.tsx
_includes/doc.tsx
deno.lock

to make the doc template easier to read

move components into separate files 

---

deno.json
deno.lock
prism.ts
runtime/_data.ts
runtime/tutorials/how_to_with_npm/create-react.md
runtime/tutorials/how_to_with_npm/react.md
runtime/tutorials/index.md

This PR adds a new react tutorial which uses a template repository 
It also updates the former react tutorial to mention the need to disable the deno vscode extension

React tutorial denojson

---

learn/_components/LearningList.tsx
learn/tutorials/_data.ts

- Adds new section to learning list
- Adds all of Eve's videos
- Adds video type icon in learning list

Include videos in learning list

---

_includes/doc.tsx
learn/_pages/VideoPage.tsx
learn/index.videos.tsx
learn/tutorials/_data.ts
learn/types.ts
youtube-lite.css

- adds video page template
- adds video pages for each video entry in learning list
- updates `doc.tsx` template to conditionally make space for a ToC only of one is passed to it

Video page template

---

runtime/fundamentals/linting_and_formatting.md

fixes https://github.com/denoland/docs/issues/1193

add link to lint site

---

deploy/manual/environment-variables.md

Fix typo in environment-variables.md

---

runtime/reference/cli/fmt.md

Fixes https://github.com/denoland/docs/issues/1244

fix: missing fmt redirect

---

runtime/fundamentals/node.md
runtime/reference/migration_guide.md

This was missing https://github.com/denoland/deno/issues/27385

Deno 2 migration guide - Add section on auto-install

---

runtime/reference/cli/coverage.md

See https://github.com/denoland/deno/pull/26590 and https://github.com/denoland/deno/issues/16626

docs: docs for coverage ignore comments

---

_components/SearchInput.tsx

- open google search results in new browser tab
- update order of search params and remove protocol

Minor google search iteration

---

runtime/contributing/building_from_source.md

This would make it easier to prevent build issues [such as this](https://github.com/denoland/deno/issues/27529).

docs: Add note suggesting WSL should have 16GB of swap space

---

runtime/_data.ts
runtime/fundamentals/open_telemetry.md
runtime/reference/cli/unstable_flags.md

Add docs for OpenTelemetry in Deno

---

README.md

Instructions for previewing JSDoc info and examples

---

_includes/lintRule.tsx

Revert "lint: show how to use a lint rule"

---

_components/Header.tsx
_components/Sidebar.tsx
runtime/_data.ts

Rename navigation links from "Runtime" to "Manual"
And remove an unused import in data.ts

update navigation text and remove unused import

---

runtime/fundamentals/security.md

Should also match the anchor at https://github.com/denoland/docs/blob/main/go.json#L4

Expand FFI in security.md

---

_components/Footer.tsx
deploy/kv/manual/cron.md
deploy/kv/tutorials/schedule_notification.md
deploy/manual/pricing-and-limits.md
runtime/index.md

Same with https://github.com/denoland/deno/pull/27726 .

chore: update redirected links

---

deploy/manual/regions.md

Closes https://github.com/denoland/deploy_feedback/issues/793

fix: update Deno Deploy region list

---

runtime/reference/cli/unstable_flags.md

Fixes https://github.com/denoland/docs/issues/1368

fix: add docs for `--unstable-node-globals`

---

runtime/fundamentals/modules.md

Add Overriding Dependencies section

---

runtime/reference/documentation.md

https://github.com/denoland/deno/pull/25220 completed this work but the documentation says it is still a WIP

update documentation for Documentation Tests

---

examples/scripts/postgres.ts

Use the npm package for postgres rather than an HTTPS import

Update example to use npm package for postgres

---

examples/scripts/import_export.ts

Update to use JSR and remove https import example

Replace https import with the JSR example

---

runtime/reference/cli/task.md

Update 'deno task' reference for wildcards

---

runtime/reference/cli/unstable_flags.md

Remove --unstable-byonm

---

examples/_data.ts
examples/scripts/checking_directory_existence.ts
examples/scripts/checking_file_existence.ts

- Updates the language and details of the example foe checking a file exists
- Adds an example for checking a folder exists

Update examples: file exists, folder exists

---

runtime/_data.ts
runtime/reference/cli/clean.md

- add `deno clean` reference page
- add `deno clean` to nav sidebar
fixes #976

add deno clean command to site and sidebar

---

_includes/layout.tsx

May close no.1423, but need to verify in prod. 
https://github.com/denoland/docs/issues/1423

Fix broken js/darkmode link

---

runtime/reference/cli/task.md

Closes: https://github.com/denoland/deno/issues/27166

update docs to explain running node commands with deno

---

lint/index.tsx

Closes https://github.com/denoland/docs/issues/1455

Show names on lint rule page

---

examples/videos/interoperability_with_nodejs.md

- Examples and transcript added to `/examples/interoperability_with_nodejs/`

Adds content to interoperability_with_nodejs video page

---

examples/scripts/sqlite.ts

I might've been wrong, but this comment seemed stale now.

fix: remove reference to jsr:@db/sqlite

---

_components/TableOfContents.css
_includes/doc.tsx

make examples pages wide

---

runtime/reference/web_platform_apis.md

Docs feedback noted that the links on this page are broken

fixing broken links

---

styles.css

Closes https://github.com/denoland/docs/issues/1492
Before:
After:

Fix border colour on dark mode (and also looks fine in light mode)

---

runtime/fundamentals/node.md

Also moves the Node built-ins link further down, to a more relevant section.

Add simple intro paragraph

---

_includes/doc.tsx

Fixes https://github.com/denoland/docs/issues/1511

fix: lint rule edit link

---

_components/SecondaryNav.css

fix sub-nav max-height

---

_components/CTA.css
_components/CTA.tsx
runtime/fundamentals/linting_and_formatting.mdx
runtime/fundamentals/standard_library.mdx
runtime/reference/deno_namespace_apis.mdx
runtime/reference/web_platform_apis.mdx
styleguide/components.mdx
styles.css

make button into component, add button to lint page

---

runtime/fundamentals/open_telemetry.md

Fixes: https://github.com/denoland/docs/issues/1502

correct status code attribute

---

styles.css

fixes: https://github.com/denoland/docs/issues/1492
old: 
new:
double check light mode:
old:
new:

fix code block border on dark mode

---

_components/TableOfContents.css

max width for toc so that it doesnt get too big, a la modules page

---

examples/tutorials/aws_lambda.md
runtime/fundamentals/testing.md

adding copy about the permissions object in deno test

adding section clarifying testing permissions object

---

examples/scripts/temporal.ts

This updates the example to console log values to show that its actually working as expected.
In addition there is a problem where the run prompt doesn't work without the flag but this will at least show that the script worked when the user passes the flag.

Update Temporal Docs

---

deno.json
deno.lock
reference_gen/deno.jsonc
reference_gen/deno.lock

ref https://github.com/denoland/deno/issues/28504

bump node types (attempt 2)

---

examples/_components/ExamplePage.tsx

Closes: https://github.com/denoland/docs/issues/1594
Old:
New:

fix look of link

---

examples/tutorials/cloudflare_workers.md

You can verify this to be accurate here: https://denoflare.dev/cli/

docs: Updated the version of denoflare cli

---

examples/scripts/duckdb.ts

Update duckdb example to use package on jsr.io

Update import to use package on jsr.io

---

runtime/reference/cli/serve.md

update deno serve documentation to mention the satisfies type

---

runtime/reference/cli/compile.md

There may well be more...
Closes https://github.com/denoland/docs/issues/102

add list of things not supported in compiled apps

---

runtime/fundamentals/workspaces.md

closes https://github.com/denoland/docs/issues/1639

add info about workspace specifiers.

---

runtime/contributing/style_guide.md

Closes https://github.com/denoland/docs/issues/222

Give a little explanation of why no top level arrow functions

---

runtime/fundamentals/modules.md

closes https://github.com/denoland/docs/issues/287

add info about data imports

---

runtime/fundamentals/http_server.md

Closes https://github.com/denoland/docs/issues/440

update info about deno serve default export

---

examples/tutorials/bdd.md

Here's a PR to fix 2 little typos I came across when reading the BDD docs.

fix bdd.md typos

---

_components/RefHeader.tsx
examples/_components/ExamplePage.tsx

Old: 
New:
Old:
New:
Closes #1700 and #1699

fix unaligned subnav links and misplaced edit on github link

---

_components/Feedback.tsx
deno.lock
middleware/functions/feedback.ts
types.ts

Updated form:
Feeback example:

move feedback over to github

---

deploy/early-access/_data.ts
deploy/early-access/changelog.md

- adds a changelog page to the EA docs to show latest progress
closes: #1755

Added changelog page and updated navigation

---

examples/videos/configuration_with_deno_json.md

Towards #1720
Added transcript and code snippets.

Added transcript and code to `examples/videos/configuration_with_deno_json.md`

---

deploy/early-access/support/index.md

add email address

---

styles.css

Fixes #1727
OLD:
NEW:
and double checking light mode:
NEW:

border colour on dark

---

runtime/reference/env_variables.md

Very minor wording update on the env variables page to make example stand out clearer

update wording slightly

---

examples/tutorials/nuxt.md

Updated tailwind section of Nuxt tutorial

---

runtime/fundamentals/node.md
runtime/reference/cli/_commands_reference.json

Ref:
- https://github.com/denoland/deno/pull/29586

add docs for --unstable-node-conditions

---

runtime/fundamentals/workspaces.md

Closes https://github.com/denoland/docs/issues/1585

updating workspaces file to mention directory pattern matching

---

examples/tutorials/nuxt.md

Updated the wording a little to match our new styleguide, double checked that the tutorial still works and is up to date, which it is.
Closes [#1707](https://github.com/denoland/docs/issues/1707)

Nuxt tutorial

---

runtime/reference/bundling.md

Fixes https://github.com/denoland/docs/issues/1867

fix: code block syntax highlight

---

examples/tutorials/prisma.md

This PR updates the Prisma + Oak REST API tutorial to work with current versions and fix compatibility issues.
- Updated to Prisma Client `^6.11.0` (latest stable)
- Now uses native `Deno.env.get()` instead of outdated methods
- Updated to use `await context.request.body.json()` (current standard)
- Fixes broken POST `/dinosaur` endpoint instructions
- All code snippets now use current APIs
- Ensures copy-paste functionality works
Addresses feedback from [issue #1862](https://github.com/denoland/docs/issues/1862) regarding tutorial updates needed for current Prisma Deno runtime support.
Tutorial now works out-of-the-box with current Deno, Prisma, and Oak versions.

fix: update tutorial Prisma

---

deploy/early-access/_data.ts
deploy/early-access/reference/databases.md
deploy/early-access/reference/index.md

https://docs--ea-databases.deno.deno.net/deploy/early-access/reference/databases/

Feat: Deploy EA Databases

---

examples/_data.ts
examples/tutorials/llm.md

Add a new tutorial for creating a chat app which responds to you with messages from an LLM

Llm tutorial

---

styles.css

Fix for clickability of embedded YouTube videos.

fix: adjust z-index to make YouTube videos clickable

---

_components/SidebarNav.tsx
static/js/sidebar.client.js
styles.css

Its not the most beautiful fix, but it stops the animation

update accordian to not animate on page load

---

examples/tutorials/next.md

Revert "commonjs flag no longer necessary"

---

deploy/early-access/reference/env-vars-and-contexts.md

`DENO_DEPLOY_REVISION_ID`  -> `DENO_DEPLOY_BUILD_ID`:

Update name of build id env var

---

runtime/fundamentals/modules.md

closes https://github.com/denoland/docs/issues/2536

patch field has been renamed to links

---

examples/scripts/hashing.ts

closes #2444 (confusion around where the std library is)

add link to standard library

---

_components/Footer.tsx

perhaps we can add a meet the team page later

removing careers link for now, 

---

deploy/reference/runtime.md

- Updates documented runtime version to 2.5.0
- Adds link to the runtime section of the docs

Update advertised runtime version
