runtime/manual/getting_started/installation.md
- Reverts #63.
- https://winget.run does not seem to be involved with Microsoft or the [`winget` cli](https://github.com/microsoft/winget-cli).
- [winget's deno versions are current](https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/DenoLand/Deno)
=> Add installation instructions using winget for Windows

LICENSE, README.md
This should integrate git history from the original Deno manual to the repository. Running:
```
git shortlog -s -n
```
Should now correctly list historical contributors.
=> Add manual commit history

runtime/manual/getting_started/configuration_file.md, runtime/manual/node/npm_specifiers.md
Reapply changes from https://github.com/denoland/manual/pull/689
- Should contain approximately the same content with updated relative links and syntax highlighting
- Should properly attribute original contributor in git
=> Rework npm specifiers

.github/workflows/update_versions.ts
This way we don't need to give denobot write permissions to this repo.
=> ci: use a fork for denobot bumping versions

kv/manual/_admonition.mdx, kv/manual/data_modeling_typescript.mdx, kv/manual/index.mdx, kv/manual/key_expiration.mdx, kv/manual/key_space.mdx, kv/manual/on_deploy.mdx, kv/manual/operations.mdx, kv/manual/secondary_indexes.mdx, kv/manual/transactions.mdx
Fixed a typo in the KV beta admonition, factor into a partial and reuse instead.
=> fix typo, factor out admonition

kv/manual/index.mdx
This commit addresses a minor issue in the Deno documentation manual related to the `kv` variable. The code example provided had an incorrect reference to the variable used to open the key-value store. The variable should be `kv`, not `db`.
**Changes Made:**
- Corrected the variable name from `db` to `kv` in the code example.
- Verified the correctness of the code snippet.
=> docs: Correct code example for `kv` variable in manual

kv/manual/index.mdx
Update index.mdx - Correcting the variable name in the example of kv get function
=> fix: variable name in the example of kv get function

runtime/manual/runtime/workers.md
https://discord.com/channels/684898665143206084/1151939558548709486/1151943237339197450
> Andreu Botella (they/them)
— 
14/09/2023 15:11
it used to be that you couldn't use workers, but now you can if you pass the `--include` flag with the worker scripts you will use
I guess the documentation is stale on that
=> update: workers now work in compiled executables

runtime/manual/runtime/ffi_api.md
close #105 
I'm not familiar with ffi but isize is also used in the sample code, and I confirmed that rust / c example code runs successifully with isize arguments.
=> fix(ffi): Add isize to list of supported FFI types

src/css/custom.css
Closes https://github.com/denoland/deno-docs/issues/28
A quick and simple fix to make code blocks extend to the edge of mobile viewports. (Also removes the rounded corners on mobile, since it looks weird to round into the edges.)
=> Extend code blocks to edge of mobile viewport

runtime/manual/advanced/jsx_dom/twind.md
Closes #89 
This PR updates twind version to `1.1.3`.
The example code is based on [extract function in @twind/core](https://twind.style/packages/@twind/core#extract).
I adjusted the code so that the HTML looks the same as before.
=> fix(example): update twind to 1.1.3

src/css/custom.css, src/theme/DocBreadcrumbs/Items/Home/index.js, src/theme/DocBreadcrumbs/index.js, src/theme/DocBreadcrumbs/styles.module.css
- Shows breadcrumbs at all times (unless the user is on a landing page and hasn't begun to navigate any deeper yet)
- Changes the "home" link in the docs to go to the current section's home (`/kv`, `/runtime`, or `/deploy`, as the case may be)
- Slightly modifies styling of breadcrumbs
=> Customize docs breadcrumbs

runtime/manual/node/compatibility.mdx
That PR fix wrong compatibility info about `node:dgram`. In fact, the realization is quite partial and most popular libraries using `dgram` not working in Deno.
Proof: https://github.com/denoland/deno/issues/18324#issuecomment-1478034481
Some issues with `dgram`: https://github.com/denoland/deno/issues?q=dgram
=> fix: wrong `dgram` compatibility info

runtime/manual/tools/script_installer.md
I just fixed the sample command to work properly.
The prior command:
```bash
deno install --allow-net --allow-read https://deno.land/std/http/file_server.ts -f -p 8080
error: unexpected argument '-p' found
tip: to pass '-p' as a value, use '-- -p'
Usage: deno install [OPTIONS] <cmd>...
For more information, try '--help'.
```
The updated command:
```bash
deno install --allow-net --allow-read https://deno.land/std/http/file_server.ts -f -- -p 8080
✅ Successfully installed file_server
/Users/motoyakondo/.deno/bin/file_server
```
=> docs: fix a command to work properly

runtime/manual/references/contributing/style_guide.md
The current link returns a `404`.
=> docs: fix link to Chromium inclusive code guide

runtime/tutorials/how_to_with_npm/prisma.md
Remove mentions of Prisma Data Proxy in favor of Prisma Accelerate.
=> docs: update Prisma guide to use Accelerate

runtime/manual/basics/testing/assertions.md
Small oversight in [Assertions](https://docs.deno.com/runtime/manual/basics/testing/assertions#throws) documentation.
=> If using await in test make test callback async

runtime/manual/basics/testing/index.md
I wrote a code example a long time ago that uses Skypack URLs. Because that no longer seems to be actively maintained I updated them to npm: imports, which also works.
=> chore: update skypack imports to npm: imports

deploy/manual/pricing-and-limits.md
Make https://docs.deno.com/deploy/manual/pricing-and-limits link to https://docs.deno.com/deploy/manual/fair-use-policy.
=> fix: update broken fair use policy link

runtime/manual/node/compatibility.mdx
I compared the latest Node.js docs and the latest Deno runtime, and these APIs seemed still missing.
I opened the corresponding issue in Deno CLI repo. https://github.com/denoland/deno/issues/21378
closes #205
=> Update node:util compatibility info

runtime/manual/advanced/jsx_dom/overview.md, runtime/manual/advanced/typescript/overview.md, sidebars/runtime.js
WebAssembly should never be spelled as two words.
=> Fix spelling of WebAssembly

docusaurus.config.js, src/client_plugins/trackjs.js, src/theme/Layout/index.js, static/trackjs.js
Add client side error tracking - primary target right now is to isolate the errors with syntax highlighting that are happening intermittently.
=> add trackjs integration for client-side errors

runtime/manual/getting_started/configuration_file.md, runtime/manual/tools/index.md, runtime/manual/tools/unstable_flags.md, sidebars/runtime.js
This will add a page to the CLI reference with unstable feature flags. I am using the flags described in the 1.39 `deno --help` output, and adding some example usage for each.
=> Add docs page for unstable feature flags

runtime/manual/node/index.md
Fixes #236 - adds a paragraph to the node compat docs section to point out existence of unstable feature flags that may improve compatibility.
=> link to unstable features from node docs

runtime/manual/tools/unstable_flags.md
It being there might give the impression it's required, but it can work exactly like as in Node.
=> Remove `npm:` prefix on unstable-byonm example

deploy/manual/index.mdx, runtime/manual/getting_started/installation.md, runtime/manual/index.md
The URL of installation uses `https://deno.land/install.ps1` for `.ps1` and `https://deno.land/x/install/install.sh` for `.sh`.
I think it's better if both URLs are of the same type.
=> Use shortened URL for install.sh

runtime/manual/references/contributing/index.md
As a beginner, I didn't even know I needed `--recurse-submodules` to clone project and to install many tools before running `cargo test`. This prompt can prevent beginners like me from feeling discouraged right from the start.
This may related to issue: https://github.com/denoland/deno/issues/21652
=> Add link to install necessary tools for contributing

src/css/custom.css, src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
Let's get rid of this cheesy web 2.0 skeuomorphism stuff.
Let's also add a back arrow to the "all docs" button.
=> Unstyle search bar and make main docs button more clearly a back button

runtime/manual/tools/unstable_flags.md
Ref https://github.com/denoland/deno/pull/21891
=> Remove --unstable-workspaces flag

deploy/tutorials/tutorial-dynamodb.md
The dynamodb client served via skypack [has issues](https://github.com/denoland/deploy_feedback/issues/116). By updating the import to use the client served on esm.sh, the issues are resolved.
=> Fix import statement in dynamodb tutorial

runtime/manual/tools/unstable_flags.md
the description for [`--unstable-kv`](https://docs.deno.com/runtime/manual/tools/unstable_flags#--unstable-kv) links to [Deno.cron](https://docs.deno.com/deploy/kv/manual/cron) and not [deno KV](https://docs.deno.com/deploy/kv/manual/cron)
=> `--unstable-kv` description incorrectly links to deno.cron

runtime/manual/runtime/workers.md
Syntax highlighting on the [deno-docs site](https://docs.deno.com/runtime/manual/runtime/workers) for these two code blocks was missing. Not sure if the ignores were there on purpose
| Before | After |
| ------- | ----- |
| ![image](https://github.com/denoland/deno-docs/assets/22731314/2d562874-9a2f-4ad0-95b2-a48590c5a850)    | ![image](https://github.com/denoland/deno-docs/assets/22731314/4a10414b-fa0f-4ac5-a2bf-9f7e73802ecc)   |
|  ![image](https://github.com/denoland/deno-docs/assets/22731314/2ade75a6-7d28-40b7-b86d-659beb3a8cc5) | ![image](https://github.com/denoland/deno-docs/assets/22731314/be764ca9-f5ab-4047-8104-0a0975fef78c) |
The code blocks seem to work on github before these changes were made
=> fix: syntax highlighting on workers example

static/fonts/inter.css
After my testing, I found that using `font-feature-settings: "cv10" on` when translating, it will cause simplified Chinese to be displayed as traditional Chinese. 
It would be strange to use software such as Google Translate to translate web pages in full screen. 
Therefore, I have adjusted `cv10` to `cv09`, and I believe it will not have much impact.
=> Fix the issue of displaying Traditional Chinese when using Google Translate to Simplified Chinese in Mac

src/css/custom.css
- Fix some overrides that weren't working
- Make the alert background color a bit more pleasant in light mode
Old on left (darker alert; tighter spacing for code blocks); new on right:
=> Minor styling updates

runtime/manual/advanced/migrate_deprecations.md
Depends on https://github.com/denoland/deno/pull/22274
Towards #297
PTAL @bartlomieju or @kwhinnery
=> docs: `Deno.ConnectTlsOptions.{certFile,privateKey}` deprecation migration guides

runtime/manual/getting_started/command_line_interface.md
This is the follow-up PR for the introduction of the `--watch-exclude` flag in Deno
[Deno PR](https://github.com/denoland/deno/pull/21935)
=> feat(run): Add watch-exclude flag

runtime/manual/advanced/typescript/configuration.md
markdown tables are…not the easiest to style. I apologise for this "fix".
Problem:
Solution:
=> the content in columns 1 and 2 needs to not wrap. 

deploy/kv/manual/cron.md
3 changes in this PR:
* Add a note about 1-based day-of-week representation
* Remove reference to https://crontab.guru (since it uses 0-based day-of-week)
* Mention JS objects syntax
=> update cron docs

runtime/manual/advanced/continuous_integration.md
Yesterday I've configured Github workflows on my OSS for the first time. I don't have paid subscription, and when I followed instructions from docs, the actions were not triggered. I believe that's because I don't have access to specific runners, I can only use `*-latest` runners:
After I've changed to `ubuntu-latest`, actions were properly triggered. If it makes sense, I would propose to use `*-latest` in docs, that way it should be always up-to-date.
=> docs: update gh runner specific os versions to latest

runtime/manual/getting_started/installation.md
* Add `asdf install deno latest` line to macOS instructions
* Remove duplicate `asdf install deno latest` line from Linux instructions
* Make the macOS instructions and Linux instructions match
* Clarify misleading comments
=> Update asdf instructions in installation.md

deploy/kv/manual/index.mdx
This is easily apparent to users who are already familiar with SQLite, but people who either don't know about ":memory:" or who aren't aware that Deno KV is based on SQLite when run locally may not be able to figure this out for themselves.
I wasn't sure whether to include the assert import for the testing example; if that's needed I can add it.
=> Explain how to test Deno KV code locally

runtime/manual/references/contributing/building_from_source.md
`002_hello.ts` was recently moved from `cli/tests/testdata/run/` to `tests/testdata/run/` in this PR https://github.com/denoland/deno/pull/22369
=> fix file path reference in building_from_source.md

runtime/manual/basics/import_maps.md
Closes https://github.com/denoland/deno_std/issues/4728
=> docs: update `deno_std` and import map docs

.github/workflows/update_versions.ts, replacements.json
`getLatestTagForRepo("deno_std")` gets the latest tag from `deno_std` repo, but the latest release tag is not the latest version of `deno.land/std` anymore since the release https://github.com/denoland/deno_std/pull/4689
This PR fixes it.
related https://github.com/denoland/deno_std/issues/4728
=> fix: the version number of `/std` and `update_versions.ts`

src/components/DenoByExample/ByExample.tsx
I reported this as issue #470, but it was easy enough to fix, so here's my solution. If there's a better way, let me know, I can update it. Thanks!
=> fix: deno run examples should point to raw githubusercontent domain

runtime/manual/getting_started/command_line_interface.md
Fig was [acquired by Amazon](https://fig.io/blog/post/fig-is-sunsetting) and is sunsetting in September 2024:
From [fig.io](https://fig.io/):
> Dear Fig users,
> 
> Effective September 1, 2024 we will be ending access to Fig.
> 
> We encourage users to migrate to Amazon Q for command line. It’s free on the Individual tier and is designed to be faster and more reliable than Fig. To make this transition as easy as possible, users can upgrade to Amazon Q for command line directly from the Fig dashboard.
---
Since shell completions are already [documented](https://docs.deno.com/runtime/manual/getting_started/setup_your_environment#shell-completions) on the Set Up Your Environment page, I feel like it is safe to remove this Autocomplete section entirely, especially since it only gave …
=> Remove Fig autocomplete section from CLI docs

runtime/manual/getting_started/configuration_file.md
New to Deno. First time I see the `.jsonc` extension, and there's no clear homepage for it like [for JSON](https://www.json.org/).
=> Link JSONC in configuration_file.md

by-example/tcp-connector.ts
Current Link takes to non existing page:  https://docs.deno.com/tcp-listener.ts
Added link to correct page: https://docs.deno.com/examples/tcp-listener
=> Correct link for tcp listener doc

runtime/manual/tools/init.md
`deno init` no longer creates the bench file.
Output also does not include the instruction to run benchmarks.
=> fix(runtime/manual/tools/init): remove bench

_components/Header.tsx, overrides.css, styles.css, tailwind.config.js
PR to our working branch for the lume migration that just (hopefully) contains style adjustments to the reference docs. I split this out so we can decide if we want to merge these in with the rest of go-live stuff.
=> ddoc style overrides

_components/Header.tsx, overrides.css
1. Set a max width for code sample + lighten background color for monospace highlighted words
2. conditionally show the doc nav only on wide viewports, also fix mobile view.
3. more verbose nav items
=> post-launch style updates

_components/Header.tsx, overrides.css, styles.css
Adjusts some mobile styles to help with content overflow on mobile that are caused by using the character-per-line limit as max width.
fixes #547
=> fix: adjust mobile styles

runtime/manual/references/contributing/index.md
The feature flag was recently renamed from `__runtime_js_source` to `hmr`.
=> chore: update `__runtime_js_source` -> `hmr`

runtime/manual/references/contributing/index.md
Didn't know about the ability to map internal modules. This adds the missing hint to the docs.
=> chore: add hint for mapping internal modules

overrides.css
Note: this should say "Usage in Deno" though that change has to happen in @denoland/deno_doc
fixes #536 #538
=> Node usage styles

runtime/manual/references/contributing/index.md
Add a quick section on how to use development builds of the LSP in vscode.
=> doc: add LSP canary section to contribution guide

_components/Header.tsx
The sidebar that is supposed to render as a button in the header during mobile view currently doesn't render, this fixes that by matching the casing of the prop as referenced in the parent layout.
=> fix sidebar in the header

_components/Header.tsx
I think I introduced this by accident in another PR but the primary nav should be a bit bigger than secondary nav font size to show that there is hierarchy to the navigation bars.
=> Fix nav item sizing

by-example/http-server-routing.ts, by-example/http-server-websocket.ts, by-example/parsing-serializing-yaml.ts, by-example/websocket.ts
I found dead URLs on the following pages.
https://docs.deno.com/examples/http-server-routing/
https://docs.deno.com/examples/http-server-websocket/
https://docs.deno.com/examples/parsing-serializing-yaml/
https://docs.deno.com/examples/websocket/
=> fix: update link url

by-example/path-operations.ts
The current example uses outdated `path.win32` and `path.posix` objects, which were deleted in https://github.com/denoland/deno_std/pull/4953. This PR updates them to the appropriate alternatives.
=> Update path-operations example

_includes/doc.tsx, styles.css
This ensures that the navigation text on the doc nav buttons truncates so one button doesn't have more height than another.
=> truncating navigation buttons

_components/Header.tsx, _components/Sidebar.tsx, _includes/doc.tsx, overrides.css, styles.css
This PR updates a number of nav styles on both the top nav and side nav
- Content is re-arranged to group runtime and deploy content
- Style changes to fix alignment at different mobile viewports
- More subtle active state accent underlines
- Search box resizing 
- Slight spacing adjustments around logo
- Removed header since there is only one section of content and every item is in that section
- Spacing changes to adjust for that.
- ToC width reduced since the table of contents only provides one level of navigation with no subnav content and thus don't utilize the arrow > icon like the rest of the docs do.
- Body content spacing adjustments to account for changes to ToC
=> Navigation Updates

_components/Header.tsx
accidentally removed this when refactoring the header and didn't realize it was needed until I added a nav item comprised of two words
=> prevent link text in nav from wrapping

README.md
There were a few lingering docusaurus references in our readme, this removes them.
=> update readme to remove docusaurus references

examples.page.tsx, index.page.tsx
Updates the links that render in the hamburger menu when you're on the index page or the examples page to match the ordering of items in the standard desktop-width navigation
=> mobile sidebar update for index and examples

runtime/manual/advanced/typescript/types.md
The sentence:
> I have a JavaScript **modules**...
Should read:
> I have a JavaScript **module**...
The sentence:
> ...will accept quoted and **non-question** values...
Should most likely read (given the context):
> ...will accept quoted and **non-quoted** values...
=> doc: fix typos in types.md

runtime/manual/getting_started/installation.md
A few days ago, an app with "denoiser" in its name was uploaded to Microsoft Store, causing winget to fail when trying to install Deno using the current command in the documentation.
Replacing the command with the full ID will fix this problem.
```
$ winget install deno
Multiple packages found matching input criteria. Please refine the input.
Name              Id            Source
---------------------------------------
AI Image Denoiser 9PPNM05292R2  msstore
deno              DenoLand.Deno winget
```
=> Replace winget commands with full ID in installation.md

runtime/manual/references/contributing/building_from_source.md
Adds instructions for building from source when the change-set spans multiple crates.
=> doc: Add instructions for building from source

runtime/manual/basics/testing/coverage.md
Updated "Test Coverage" article with `--clean` flag from the [Deno v1.44 post](https://deno.com/blog/v1.44).
=> docs: Add --clean flag to coverage docs

_config.ts
There are a few broken images as a result of /deploy/manual/images being left out of the config. this fixes that.
=> add image directory for missing deploy manual images

styles.css
adds an active state to the links in the category panel now that deno_doc supports that functionality
=> add active states to categorypanel

overrides.css, styles.css
This adds style overrides to render the APIs in a single column layout with some adjusted spacing to account for the new layout.
=> switch APIs to single col layout

runtime/manual/tools/index.md
Compared this content to `deno -h` and updated accordingly. Note that I linked `add` and `publish` to docs in other parts of the manual tree. On the fence if that's lazy or clever - but the linked sections contain useful content that seemed unnecessary to duplicate.
=> fix: add missing cli subcommands and update descriptions

index.page.tsx
fixing the link to the hello world example on the homepage
=> fix hello world link

runtime/tutorials/unix_cat.md
which explains writable but does not have its own link
=> update to stdout page,

_config.ts
This PR adds missing highlighting for `.json` files.
Before:
After:
=> fix: missing json syntax highlighting

runtime/manual/runtime/import_meta_api.md
Fixes https://github.com/denoland/docs/issues/667
=> chore: update import.meta API code blocks

_components/Sidebar.tsx, _includes/doc.tsx, overrides.css, styles.css
Two instances of removing light pink from our UI since we've settled into using blue as our primary color until the new dotcom is done.  
Also fixed some nearby minor spacing issues with the docs content body where content was too close to the sidenav at the largest viewport
=> Adjust sidenav and details colors

runtime/manual/references/contributing/building_from_source.md
Updates the contributing guide to provide details on how to run both the Rust and TypeScript tests.
https://github.com/denoland/docs/issues/718
=> doc: provide details for running the tests

.vscode/settings.json, examples.page.tsx
Fixes the sort order for Examples categories. Also adds some VS code autosave settings so personal "format on save" preferences don't overwrite the docs settings. (As a consequence, there are several `fmt` changes lumped in here, but the sort order thing is the only actual user-facing code change.)
=> Fix examples sort order

examples.page.tsx, styles.css
Fixes double underline on header anchor links.
Establishes a new code block style (light mode only for now)
And some small style changes to the search input
=> Code block styles, fix anchor links, improve search input

deno.json, lume.ts
Makes it easier to pass profiling flags to `deno run`
=> chore: use real lume entry for easier profiling

server.ts, subhosting/manual/index.md
A customer contacted Stainless asking for them to generate a JS SDK from the Subhosting API, citing that they did not see a mention of one in our docs.
=> Add links to Subhosting SDKs

runtime/manual/node/cheatsheet.md
replace process.exist to process.exit
=> fix: typo in node cheatsheet

examples/cron.ts, examples/kv-watch.ts, examples/kv.ts, examples/queues.ts, examples/udp-connector.ts, examples/udp-listener.ts
Update `--unstable` flag on examples page.
=> fix: migrate to granular `--unstable-*` flag

runtime/manual/tools/unstable_flags.md
This updates to include `--unstable-http` on the unstable page, which isn't otherwise explained in the docs. (reference: https://github.com/denoland/deno/blob/main/runtime/js/90_deno_ns.js#L293)
=> docs: add `--unstable-http`

runtime/manual/basics/modules/index.md
=> docs: fix typo

examples/cron.ts
Using the wrong unstable option.
=> docs: fix unstable option

runtime/fundamentals/security.md
- reoder
- remove `--allow-hrtime` (it's already gone in latest canary)
- remove "unstable" notification for `--allow-ffi` (it's stable in latest canary)
=> Fundamentals - Security

deploy/manual/acceptable-use-policy.md
Updating the acceptable use policy documentation to clarify the acceptable and unacceptable use of deploy for proxy use cases.
=> docs: clarify acceptable use policy on proxy's

styles.css
Restyles the tabbed content in the docs to make it more obvious that tabs exist and better highlight the different types of content inside.
=> Tabbed content refresh

_components/Header.tsx, _components/Sidebar.tsx, _includes/doc.tsx
Changes up the breadcrumb style a little bit to make the underline stand out less and give some better hover to both breadcrumb and main nav.
Switches main nav from box borders to text decoration to make it a bit less bouncy and accommodate background-color hover states
Also resizes the main content area padding a bit to line up side nav items and breadcrumb better.
=> Improving breadcrumbs

_includes/doc.tsx, styles.css
Adjust spacing between headers and paragraphs to be a bit closer to what we had on Docusaurus
New on left
Old on right
=> adjust header spacing in markdown content

examples/permissions.ts
I did "Permission Management" example.
I met error. See below. This pull request will fix the error.
Please check it out.
```sh
deno run https://docs.deno.com/examples/permissions.ts
error: Unknown export './assert.ts' for '@std/assert@1.0.3'.
Package exports:
* .
* ./assert
* ./almost-equals
* ./array-includes
* ./equals
* ./exists
* ./false
* ./greater
* ./greater-or-equal
* ./instance-of
* ./is-error
* ./less
* ./less-or-equal
* ./match
* ./never
* ./not-equals
* ./not-instance-of
* ./not-match
* ./not-strict-equals
* ./object-match
* ./rejects
* ./strict-equals
* ./string-includes
* ./throws
* ./assertion-error
* ./equal
* ./fail
* ./unimplemented
* ./unreachable
at https://docs.deno.com/examples/permissions.ts:45:24
```
=> Fix: error: Unknown export './assert.ts' for '@std/assert@1.0.3'.

runtime/tutorials/digital_ocean.md, runtime/tutorials/file_server.md, runtime/tutorials/file_system_events.md, runtime/tutorials/google_cloud_run.md, runtime/tutorials/hashbang.md, runtime/tutorials/hello_world.md, runtime/tutorials/kinsta.md, runtime/tutorials/os_signals.md, runtime/tutorials/read_write_files.md, runtime/tutorials/subprocess.md, runtime/tutorials/tcp_echo.md, runtime/tutorials/unix_cat.md, runtime/tutorials/word_finder.md
Mostly some formatting changes before doing bigger ones later in a future PR.
- Update `HTTP file server` doc
- Update `cat tutorial`
- Add file titles to code blocks
=> docs: fix tutorial code block titles

_components/Footer.tsx
`www` doesn't seem to connect to deno status.
=> fix: invalid deno status link

runtime/manual/advanced/migrate_deprecations.md
Also includes other corrections.
=> docs: add `Deno.fsync[Sync]()` and `Deno.fdatasync[Sync]()` to "Deno 1.x to 2.x Migration Guide"

deploy/manual/privacy-policy.md
The linkify option creates http links when it detects bare links inside markdown. This is unintentional in this case, so using a `\` escape avoids that.
=> docs: fix http link in privacy policy

runtime/manual/help.md
The `oldUrl` referred to itself which caused an infinite redirect.
=> fix: infinite redirect

deploy/api/index.md, deploy/api/runtime-broadcast-channel.md, deploy/api/runtime-fs.md, deploy/api/runtime-node.md, deploy/manual/ci_github.md, deploy/manual/index.md, deploy/tutorials/tutorial-postgres.md, deploy/tutorials/vite.md, runtime/fundamentals/modules.md, runtime/fundamentals/testing.md, runtime/reference/deploying_and_embedding.md, runtime/tutorials/how_to_with_npm/apollo.md, runtime/tutorials/how_to_with_npm/express.md, subhosting/manual/quick_start.md
The wrong property name was used in the front matter which lead to the redirects not being picked up. Rest is the usual missing 404s
=> fix: broken redirects

styles.css
Noticed that our CSS file has a syntax error. This error was introduced in https://github.com/denoland/docs/pull/843
=> fix: missing closing curly brace for CSS block

runtime/reference/migrate_deprecations.md
This method is no longer being removed in Deno 2.
=> docs: remove migration guide for `Deno.FsWatcher.prototype.return()`

overrides.css
An idea for a restyled usage block makes it feel more like a labeled content block than a random floating header that's missing paragraph text below
=> Restyle "usage in deno" node reference

runtime/fundamentals/testing.md, runtime/fundamentals/typescript.md, runtime/reference/cli/check.md, runtime/reference/cli/test.md
We landed "true" doc testing in https://github.com/denoland/deno/pull/25220. With this change, `deno test --doc` will actually _run_ code snippets written in JSDoc or markdown files, as well as type checking. This commit updates the corresponding doc pages to follow this change.
Preview of the updated pages:
- https://deno-docs--magurotuna-improved-doc-te.deno.dev/runtime/fundamentals/testing/#documentation-tests
- https://deno-docs--magurotuna-improved-doc-te.deno.dev/runtime/fundamentals/typescript/#type-checking
- https://deno-docs--magurotuna-improved-doc-te.deno.dev/runtime/reference/cli/check/
- https://deno-docs--magurotuna-improved-doc-te.deno.dev/runtime/reference/cli/test/
=> docs: modify docs on doc testing to reflect code snippet execution

_components/Header.tsx, examples.page.tsx, index.page.tsx
Main difference is in the top navbar where "Reference" was changed to "API reference".
=> Rename 'Reference' to 'API reference'

deploy/tutorials/static-site.md
Working tutorials.
- point to the latest working @std/http
- actually use a real file for the entry point, so it does not fail
> [!NOTE]
> For the latest 1.0.x version to work, see https://github.com/denoland/std/pull/6033
- Enable JSR as an entrypoint: https://github.com/denoland/deployctl/issues/304
=> docs(static-site): working example

runtime/_data.ts
This got broken by mistake by https://github.com/denoland/docs/pull/906, not yet
sure how that happened.
=> fix: Link to 'deno install' subcommand

go.json
When running `deno lsp --help` you can see this help:
> How to connect various editors and IDEs to 'deno lsp': https://docs.deno.com/go/lsp
That page/redirect doesn't exists.
This PR adds a redirect for that page.
=> Add redirect for /go/lsp

runtime/_data.ts, runtime/reference/cli/all_commands.md, runtime/reference/cli/unstable_flags.md, runtime/reference/env_variables.md, runtime/reference/lsp_integration.md
Remove env variables from CLI section (same content is covered in references)
Reorder "all commands" list to match --help output
Update CLI sidebar order
Move LSP integration file into references now that its sidebar item is under Reference not CLI
=> update cli menu in sidebar

.github/workflows/link_checker.ts, deno.lock
Currently link checker causes `Reached heap limit` error in CI. This PR tries to fix it.
Currently the link checker checks all `<a>` tags concurrently (and it also does that recursively if it finds a new page). This PR limits the concurrency to 10 and tries to prevent the memory error.
(This PR also removes the `.hash` property from URL before visiting. This removes the duplicated checks of URLs which only differ in hash part.)
=> Limit the concurrency of link checker

index.page.tsx
Adds a banner to the homepage to announce 2.0
=> add temporary deno 2.0 banner

styles.css
Reduce font weight on homepage links so they don't overshadow the section headers.
=> set homepage links to normal font weight

runtime/reference/migration_guide.md
fix links in "Deno 1.x to 2.x Migration Guide"
=> fix links in "Deno 1.x to 2.x Migration Guide"

deploy/manual/index.md
This addresses a issue I opened up on the docs repo.
=> Fixing the deploy example to include the --global parameter

runtime/tutorials/index.md
This pull request includes a small but important change to the `runtime/tutorials/index.md` file. The change corrects the link for the Next.js tutorial to ensure it points to the correct URL.
=> Fix: redirect for Next.js tutorial link

runtime/fundamentals/linting_and_formatting.md
We're using `dprint` in Deno, not `prettier`.
=> docs: fix wrong format engine

runtime/fundamentals/security.md
Changes the article "a" to "an" as it's more natural given this is put before the word "explicit".
=> fix article usage in `runtime/fundamentals/security`

runtime/reference/web_platform_apis.md
`:::warning` does not render properly, must use `:::caution`
=> fix: web worker permissions caution block

examples/reading-system-metrics.ts
Added a Deno example to read system metrics including memory information and load averages, with detailed comments and documentation. This example demonstrates the usage of `Deno.systemMemoryInfo` and `Deno.loadavg` for monitoring system performance.
=> docs: adds system metrics example

runtime/fundamentals/node.md
The order of the install and run commands is reversed.
=> fix: order of install/run

runtime/reference/env_variables.md
https://github.com/denoland/deno/pull/24555 added the `--env-file` flag to match other runtimes. Even though `--env` still works, `deno help` recommends `--env-file`, so there's an inconsistency between Deno's helptext and docs.
=> --env -> --env-file

runtime/reference/jsx.md
- Add output example for all the JSX transforms
- Add missing section for `"react-jsxdev"`
Fixes https://github.com/denoland/docs/issues/701
=> docs: enhance jsx page with output examples

deploy/kv/manual/key_space.md
Pluralize the `users` part of the key like the rest of the page does.
=> KV Key Space: pluralize `users` for consistency

_components/Header.tsx, _components/Sidebar.tsx, styles.css
A few design updates for the side and top nav:
- less vertical space on nav link items
- light border on hover to help identify actively hovered items vs current page
- bolded text for current page to provide a secondary means of identifying current page
- adjustments to search box to make it match some of the other grays used on the page
- lightened the divider between top nav item types so it's more clear that its a divider and not an un-rendered link
- reducing icon size for external link so it doesn't stick out so much
=> update nav design flourishes

runtime/tutorials/how_to_with_npm/vue.md
On my machine, while running through the [Deno Vue](https://docs.deno.com/runtime/tutorials/how_to_with_npm/vue/) tutorial, I needed to run `deno install` (or `npm install`) before running `deno task dev` or I would get the following error:
```
Task dev vite
vite: command not found
```
=> The Deno Vue tutorial requires installing dependencies before running

runtime/tutorials/how_to_with_npm/vue.md
This PR fixes filename typo in the VueJS examples.
The text refers to `types.ts` but the example snippet had `types.d.ts`.
While technically both should work, the `tsconfig.app.json` includes only `*.ts` files, so the filename has to be `types.ts`.
Tutorial works with the change as expected.
=> Change types.ts filename

runtime/fundamentals/configuration.md
Added a line of test stating, "Note that this will require you to run `deno install` at `/runtime/fundamentals/configuration/#dependencies`
Resolves [#1009]
=> hint at running  deno install when using a package.json

runtime/tutorials/how_to_with_npm/next.md
This PR fixes a typo caused by copy&pasting from React/Vue tutorials.
It refers to an undefined `context` variable.
Change has been tested.
=> Fixes typo in Next.js tutorial

deno.lock, examples/hono.ts
Adds a simple hello world example for [Hono](https://hono.dev/).
Just thought that since it was [announced](https://deno.com/blog/hono-on-jsr) on the Deno blog, there should be an example with explainer comments here :)
=> feat: add example for hono

_config.ts
Noticed that we weren't highlighting `.jsonc` code snippets on https://docs.deno.com/runtime/fundamentals/configuration/#custom-path-mappings .
This PR fixes that.
=> fix: missing syntax highlighting for jsonc

runtime/reference/jsx.md
This pull request includes a minor change to the `runtime/reference/jsx.md` file to improve the clarity of the documentation.
Documentation improvement:
* [`runtime/reference/jsx.md`](diffhunk://#diff-97cac2c0f6729544e9c30f793213a249111703db2bb4925872741d7926472c93L10-R10): Corrected the phrase "generating code browser" to "generating code for browser" for better readability.
=> Add missing word in JSX docs

runtime/reference/node_apis.md
Removes the duplicated `fetch` and `File` supported row from the Globals field.
=> fix(docs): Remove duplicated links in node_api docs

examples/hex-base64-encoding.ts
The current example uses old APIs (`base64.(encode|decode)`), which don't exist anymore. This PR updates them to the latest versions.
=> Update hex-base64-encoding example

index.page.tsx
Adds banner linking to the self-hosted screener before the deploy content.
=> add banner for self-hosted

runtime/tutorials/how_to_with_npm/react.md
- Corrects a typo of `som` to `some`
- Corrects the path
- From: import routeStaticFilesFrom from "./util/routeStaticFilesFrom.ts";
- To: import routeStaticFilesFrom from "./api/routeStaticFilesFrom.ts";
This aligns with the instruction above that states: "In your api directory create a new file called routeStaticFilesFrom.ts and add the following code:"
=> Correct a typo and Clarify an incorrect import

examples/rsa-signature.ts
For web cryptography signature and verification examples
=> RSASSA-PKCS1-v1_5 Signature and Verification

examples/unzip-gzipped-file.ts
I'm so sorry, at some point during development I deleted an e in the gzip example. This caused a typo in the group name which led to a new group being created.
This PR fixes that typo so it is appropriately grouped.
=> fix typo in group name for gzip example

runtime/tutorials/how_to_with_npm/react.md
so https://github.com/denoland/tutorial-with-react/tree/main/api/util  and code snippet actually works with instruction given in text.
1. file is in repo in util - folder
2. file is not in /api/api/ folder, like code snippets states.
3. text says to create file in api-folder.
https://github.com/denoland/docs/pull/1125 can be closed then. or merge both pr together, so that a good end result is reached.
=> harmonize folder structure in text and code-snippet

.github/workflows/ci.yml, deno.json, deno.lock, examples_test.ts
This PR adds test cases which check the module graphs of the example scripts are valid.
This prevents the error like https://github.com/denoland/docs/pull/1153 in the future.
=> ci: check module graph of example scripts

.github/workflows/deploy.yml, 404/index.page.tsx, _config.ts, middleware/redirects.ts, tailwind.config.js
This is an MVP, not the perfect result, but much better than what we currently have (which is nothing)
=> feat: redirect to previous path if its a 404

runtime/reference/cli/compile.md
Fixes https://github.com/denoland/docs/issues/1185
=> fix: `deno check` redirecting to `deno compile`

_components/Header.tsx, _config.ts, _includes/layout.tsx, index.page.tsx, learn/_components/EmbedVideo.tsx, learn/_components/SectionTeaser.tsx, learn/_pages/LandingPage.tsx, styles.css, youtube-lite.client.js, youtube-lite.css
First pass at the Learn landing page.
- Adds `EmbedVideo` component (scoped to the learn section for now)
- Adds `SectionTeaser` component (scoped to the learn section for now)
- Basic layout of the Landing page
Also:
- Updates the mobile nav to remove Examples and Add Learn
- Uses "Learn" in primary nav
Still todo:
- Responsive layout of the Layout page
- Copywriting for the page
- Apply consistent containing page template for the learn section to include secondary nave
=> Learn landing page

runtime/fundamentals/linting_and_formatting.md
This pull request introduces the addition of the `--unstable-sql` flag, as introduced in https://github.com/denoland/deno/pull/26750, to the options of the formatter.
=> fix: add `--unstable-sql` flag to formatter options

index.page.tsx
Prevent text inside buttons from wrapping on iPhone SE.
Current:
This PR:
=> chore: prevent button text from wrapping

examples/spy-functions.ts
Hello deno community!
I added an example for how to spy on functions using `std@testing/mock`
Related to issue #1088 
I wasn't sure in which group put this example so I kinda created a new group for 'Testing'. I want to upload another example on how to use stubs. It seems like the group should be created elsewhere in order to appear as a correct group (titlecase), I would really appreciate little help on this :)
=> docs(examples): add example for spy functions

runtime/reference/vscode.md
Addressing 2 misspellings of "lens" (not "lense") in the docs.
=> fix(docs): fix misspelling of lens in vscode.md

examples/creating-and-verifying-jwt.ts
Adds a new example demonstrating how to create and verify JSON Web Tokens (JWT) using the jose library in Deno. The example includes two main functions: createJWT for generating JWTs and verifyJWT for verifying them.
=> feat: adds JWT example

examples.page.tsx
mainly to resolve the snippet without code combining with the snippet below. Resolves #1003
=> add some margin between snippets in examples

runtime/fundamentals/security.md
I'm surprised this wasn't in the docs already. Is there a more in-depth treatment of the `--allow-env` flag somewhere else in the docs (not in [the blog post](https://deno.com/blog/v2.1#--allow-env-wildcards))?
=> docs(security): mention --alllow-env wildcards

styles.css, tailwind.config.js
Fixes the link colors on the homepage (and occasionally elsewhere) being too light/dark to contrast properly for a11y requirements.
=> Fix runtime link contrast on homepage

deploy/manual/logs.md
This commit adds a statement which clearly mentions that there is a rate limit on the number of logs generated by a deployment.
=> docs(deploy): state the limit on app log emission rate

examples/tcp-echo-server.ts
=> Remove unnecessary backtick

_components/LandingPage.tsx, deno.lock, examples/index.tsx, styles.css
- Moves the /examples `LandingPage` component into the `_components` folder so that it auto-refreshes when changes are made locally
- Fixes some CSS color values that were previously missing commas, rendering them as white
=> Move examples page; fix CSS color issues

examples/tutorials/express.md, runtime/fundamentals/node.md
`@ts-types` is now the recommended way to add types to js imports. ref https://github.com/denoland/docs/pull/502
This PR replaces the use of `@deno-types` with `@ts-types`.
(These `@deno-types` usages were pointed in https://github.com/denoland/deno/issues/27309#issuecomment-2535862020
=> Replace @deno-types with @ts-types

runtime/reference/ts_config_migration.md
This note was added in https://github.com/denoland/docs/pull/502, but removed by https://github.com/denoland/docs/pull/826 (probably by mistake?)
This note addresses the question like https://github.com/denoland/deno/issues/27309#issuecomment-2535862020
=> Restore note about @deno-types

examples/tutorials/next.md
As discussed in [#26584](https://github.com/denoland/deno/issues/26584), Next.js doesn't work properly unless using `--unstable-unsafe-proto`.
Using it from CLI isn't possible, so adding it to a `deno.json` file alongside the existing `package.json` is a working fix.
=> fix: add `unsafe-proto` flag to run Next.js app

runtime/reference/migration_guide.md
Fix explanation for nodeModulesDir migration guide following my conversation with @dsherret 
https://github.com/denoland/deno/issues/27385#issuecomment-2546157129
=> Fix explanation for migrating to Deno 2 for nodeModulesDir

examples/_data.ts
Removed what appears to be a misplaced "-tutorial" inside of the word "project."
=> Fix broken link to "Build a Fresh app" tutorial

runtime/reference/cli/bench.md
The current example in the benchmark documentation about _file reading_ breaks in the `file.close()` line. Also, I updated to include an example below of the _file reading_ bench saying that this benchmark needs the `allow-read` flag.
=> docs: update benchmark file reading example

_config.ts, deno.json, examples/_components/SnippetComponent.tsx, middleware/googleAnalytics.ts, middleware/redirects.ts, sidebar.client.ts, tabs.client.ts, timeUtils.ts
1. Remove cleaning - saves 1.5 seconds per update
2. Remove parsing all .html files to add highlighting and tabs. - highlighting configured in markdown plugin, tabs executed on client side. Additionally server side highlighting in snippet component.
3. Configured scoped updates and debounce for responsiveness.
4. Added better logging using Lume's logger.
5. Create secondary serve task which sets default log level to WARN and disables link checker plugin in dev-mode using an environment variable as it was taking over half the cycle time (5s+)
=> perf optimisations (5~7 seconds shaved off (windows))

go.json, runtime/reference/cli/lint.md
Migrates https://lint.deno.land/ignoring-rules to https://docs.deno.com/reference/cli/lint/.
That page contained more info than the current reference page.
Also added `/go/lint-ignore` for quick access.
=> lint: update ignore directives manual

lint/rules/ban-unknown-rule-code.md, lint/rules/ban-unused-ignore.md, lint/rules/prefer-const.md, runtime/fundamentals/configuration.md, runtime/fundamentals/linting_and_formatting.md, runtime/fundamentals/node.md, runtime/reference/cli/lint.md, runtime/reference/deno_namespace_apis.md
Towards migration of https://github.com/denoland/deno_lint/pull/1380
=> chore: replace lint.deno.land with /lint/ page

_components/Feedback.tsx, _includes/doc.tsx
we've expanded the max width on the rest of the content so it probably makes sense to let the feedback module and page navigation expand to the same width so they aren't oddly centered under some wider content.
Old:
New:
=> remove max-width on feedback and page nav

deploy/api/runtime-request.md
In one place it is called `input` whereas in the other it is called `resource`:
=> request constructor use same name as parameters description

runtime/fundamentals/stability_and_releases.md
We refer to the release date of v2.1 as if it were in the future, but that date has now past.
This edit removes the reference to the date being in the future on this page:
https://docs.deno.com/runtime/fundamentals/stability_and_releases/#long-term-support-(lts)
=> Edit language to remove reference to future date, which is now past

runtime/reference/cli/task.md
Following [this issue](https://github.com/denoland/deno/issues/27713#issuecomment-2599347664).
=> Clearify matching workspace member names with `task --filter`

examples/tutorials/qwik.md
The Qwik example mentioned was not working, due to incorrect data access based on the provided JSON data.
=> Fix incorrect data destructuring/access in qwik example

copy.client.ts, markdown-it/codeblock-copy.ts
ref: https://github.com/denoland/docs/issues/1292
I fixed the copy button in the tabs.
The reason the copy button in the tabs didn't work was because of the render order issue. So I moved the binding delegate to the document.
tested in local: 
https://github.com/user-attachments/assets/b016d81d-b25b-4821-a7ca-fd8e9c53de64
=> fix: restore copy button in tabs

runtime/reference/cli/compile.md
The go URL still points to the old URL, but a redirect is not in place. Since `deno compile --help` using the go URL, it is linking to a 404.
This was likely broken with #1182, when the go URL was changed, but a redirect was not added for the destination, missing that the new URL also needed a redirect.
Tested locally by visiting the `/runtime/manual/tools/compile` and `/go/compile`. 404 before, working after.
=> fix: add redirect to old url for compile docs

runtime/reference/cli/task.md
For deno workspaces name is expected to be in the tasks? or should it be a the top level in the deno.json?
=> fix: Update task.md to fix error with package name

reference/_components/DocBlockSubtitleClass.tsx
Minor style fix similar to #1370 
Fixes missing space after `implements` as seen on:
- https://docs.deno.com/api/node/fs/~/Dir
=> Add missing space after `implements` keyword

.github/workflows/deploy.yml, deno.lock
Currently gcp-metadata@6.1.1 is not compatibile with Deno. We can keep using gcp-metadata@6.1.0 by using lock file at the root.
=> chore: fix ci

deploy/manual/deployctl.md, deploy/tutorials/static-site.md, deploy/tutorials/vite.md, examples/tutorials/file_server.md, runtime/fundamentals/debugging.md, runtime/reference/cli/compile.md
- fix typo
- use latest file-server across all examples
=> docs: fix typo and update file-server examples to use latest version

lint/index.tsx
=> fix: dark mode lint rule border

runtime/fundamentals/linting_and_formatting.md
no need to confuse beginners with needless flags considering they're stabilized in Deno 2.0
- https://github.com/denoland/deno/pull/25753
- https://deno.com/blog/v2.0
=> docs(linting_and_formatting): remove stabilized flags

runtime/getting_started/installation.md
This commit fixes the install commands with `asdf` as they seem to have been updated.
Ref: https://asdf-vm.com/guide/getting-started.html#_4-install-a-plugin
=> Update install commands with asdf

examples/tutorials/prisma.md
The `--unstable` flag was removed in Deno 2.0. Replace it with the more precise `--unstable-detect-cjs` flag.
=> :memo: Prisma: Updare `--unstable` flag usage

deploy/manual/edge-cache.md
Removes the notification that the cache api is only available as part of a closed beta.
closes #1414
=> Update edge-cache advertised availabilty

runtime/fundamentals/workspaces.md
This adds a section on how to declare multiple package entries.
I feel like long term we should have a dedicated "packaging" page. Right now the only information about how to package your code is here on the workspace page.
Fixes https://github.com/denoland/docs/issues/1408
=> doc: add multiple package entries example

examples/tutorials/vue.md
Our markdown parser and syntax highlighter doesn't know how to handle `vue` as a content type.
We can just use `html` here.
fixes: #1386
=> Fix vue code fences

lint/index.tsx, runtime/fundamentals/linting_and_formatting.md, runtime/reference/cli/lint.md
- Adds a link from list of rules at `/lint` to the CLI reference page on `deno lint` at `/runtime/reference/cli/lint/`
- Makes existing link on `/runtime/fundamentals/linting_and_formatting/` page to the List of Rules pag more prominent
- Makes existing link on CLI reference page at `/runtime/reference/cli/lint/` to the List of Rules root relative
=> Add links between lint pages

deploy/manual/pricing-and-limits.md
Adds information on the RAM allocation limits in Deploy to 
https://docs.deno.com/deploy/manual/pricing-and-limits/
=> Add RAM limits info

examples/videos/deploying_deno_with_docker.md
Populates the content page to support the video at `/examples/deploying_deno_with_docker/`
=> Add content to accompany deploy to docker video

runtime/fundamentals/security.md
This PR fixes a small grammatical typo of a duplicated word “using”
Thanks for these incredible security features and great documentation on this page!
=> Fix typo in security.md

lint/rules/jsx-button-has-type.md, lint/rules/jsx-curly-braces.md, lint/rules/jsx-key.md, lint/rules/jsx-no-children-prop.md, lint/rules/jsx-no-comment-text-nodes.md, lint/rules/jsx-no-duplicate-props.md, lint/rules/jsx-no-unescaped-entities.md, lint/rules/jsx-no-useless-fragment.md, lint/rules/jsx-props-no-spread-multi.md, lint/rules/jsx-void-dom-elements-no-children.md, lint/rules/react-no-danger-with-children.md, lint/rules/react-no-danger.md, lint/rules/react-rules-of-hooks.md
- Add missing docs for new JSX rules
- Rename `no-danger` -> `react-no-danger`
- Rename `jsx-no-danger-with-children` -> `react-no-danger-with-children`
- Add missing tags to jsx rules
=> fix: add missing docs for jsx rules

examples/_components/ExamplePage.tsx, examples/_components/SnippetComponent.tsx
Trying to improve how some examples with text only snippets are displayed.
| Page | Before  | After |
| ------ | ------------- | ------------- |
| [Hashing](https://docs.deno.com/examples/hashing/)  | ![image](https://github.com/user-attachments/assets/785de5ef-c3e6-4221-b2d4-1bb6c9390368)  | ![image](https://github.com/user-attachments/assets/5cfe7571-225d-44d5-83c5-4b19c7dd637a)  |
| [Create & Remove Dirs](https://docs.deno.com/examples/create_remove_directories/) | ![image](https://github.com/user-attachments/assets/0d444701-305a-4560-b569-c20cda771682) | ![image](https://github.com/user-attachments/assets/2d3855a3-e69b-4115-a748-faeee2cc64e2) |
| [Piping streams](https://docs.deno.com/examples/piping_streams) | ![image](https://github.com/user-attachments/assets/d0e2ba95-fe40-4ee6-9117 …
=> Update style for text only snippets

runtime/reference/cli/task.md
Switch order of client and server tasks in async example to conform to the mental model a little more naturally.
=> Swap order of client and server in async example

_components/Footer.css, _components/Navigation.tsx, reference/_components/Example.tsx, static/reference_styles.css
fix footer spacing
add 'see all symbols' link back to righthand nav on reference pages
remove doubled up 'Examples header' as per https://github.com/denoland/docs/issues/1330
=> misc style updates

runtime/contributing/release_schedule.md
Update the information on deno minor release cadence to reflect the 12 weeks timetable.
Effected page: `/runtime/contributing/release_schedule/`
=> Update release cadence language

_components/Navigation.css, _components/TableOfContents.css, _includes/doc.tsx, static/style.css
Fixes the horizontal overflow issue on some pages by explicitly setting column minimum widths to 0, and by removing minimum width from the sidebars. This gives the grid full control over the column widths, and doesn't allow any grid items to force the columns to be wider.
=> Fix overflowing content

runtime/reference/lint_plugins.md
- Point to `typescript-eslint`'s playground when developing plugins
- Add note about `:exit` pseudo
=> docs: add selector tips to lint plugins

runtime/getting_started/setup_your_environment.md
Documentation added how to set up deno lsp when using the [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) neovim configuration template and Mason LSP.
=> Added documentation how to set up deno lsp in kickstart.nvim

_components/SecondaryNav.css, _components/SecondaryNav.tsx, oldurls.json
hide uncategorized category under the /api/deno section 
make deno namespace the langing page for api/deno
make width of sidebar not go below 250px so that it is the same across sections.
=> hide uncategorized and make deno namespace the langing page for api/deno

examples/videos/publishing_modules_with_jsr.md
Adds transcript and examples to the video page for `/examples/publishing_modules_with_jsr/`
=> Add transcript to video page

runtime/reference/lint_plugins.md
Hi there - I read this page while doing the [Lint Rules Contest](https://deno.com/blog/lint-rules-contest) today and based on that have made a few small changes to fix it / make it clearer:
1. Used normal type annotations for the example linter's default export, rather than `satisfies Deno.lint.Plugin` (This is because I noticed when publishing my own plugin that JSR complained about the latter being a "slow type").
2. Fixed the example test file name to use a `_` rather than `-`, so that `deno test` picks it up by default.
4. Mentioned that the filename we give to `Deno.lint.runPlugin` is just a dummy (we provide the source-code to lint as a string).
5. Fixed the assert for `Deno.lint.Diagnostic.fix` in the example test (it is never a function either way).
6. Fixed the link to the API …
=> docs(reference/lint_plugins): Clarify "Testing plugins" example

lint_rules.client.ts
The search value wasn't reset internally when it had a value and was cleared again.
Fixes https://github.com/denoland/docs/issues/1513
=> fix: lint rule search not cleared on empty input

lint/index.tsx
The lint rule filtering page inherits styles from `gfm.css`. That file includes a rule like this:
```css
.markdown-body li + li {
margin-top: ...
}
```
Which gives every lint rule item except the first a top margin. When filtering the rule list the first item is often hidden, which means that the first _visible_ item got a margin top and moved the result list around.
=> fix: lint rule items jumping around on search

runtime/fundamentals/modules.md
Per discussion in denoland/deno#28380, the actual behavior of `importMap` conforms to the Import Maps Standard, rather than the Deno extension that does away with these double entries.
=> docs: fix incorrect importMap description

_includes/renderCommand.tsx
There is a bug in calculating whether to use inline or pre code blocks.
Example: https://docs.deno.com/runtime/reference/cli/install/
The offset is used to determine where the ANSI color block match is in the reference string. If the line is a full match, a pre code block is rendered, otherwise an inline code block is rendered.
Line 87 loses the linefeed characters used in the split. The calculation was deviating slightly from the correct offset as a result. In the edge case for the inline code block near the end of a line, its type is derived from the next line, and incorrectly when the next line is a pre block.
Fix:
Tested by building locally, and spot checking other commands.
=> fix: correct code block from reference docs

index.page.tsx
Prior to this commit, the link to the websockets API page was broken (404). It was supposed to be `https://docs.deno.com/api/deno/websockets` instead of `https://docs.deno.com/api/deno/web-sockets`.
=> fix: change websockets url

runtime/fundamentals/security.md
feature was added in https://github.com/denoland/deno/pull/26938 but never documented.
=> docs: add note for DENO_TRACE_PERMISSIONS

runtime/reference/cli/completions.md
This page might warrant more information on how to persist completions after reboot, given that [bash apparently doesn't reliably source the completion scripts](https://stackoverflow.com/questions/56389011/does-bash-source-bash-completion-files-in-usr-local-etc-bash-completion-d-by-de) from `/usr/local/etc/bash_completion.d`.
=> docs(completions): intro for those unfamiliar

_components/Navigation.css
Prior to this commit, when the viewport is less than 1024px, the titles of some snippets would go on top of the sidebar. This raises the z-index of the nav sidebar so that it will always go over these texts.
=> fix: raise nav sidebar z-index

runtime/_data.ts, runtime/reference/cli/install.md, runtime/reference/cli/task.md, runtime/reference/cli/unstable_flags.md, runtime/reference/lint_plugins.md, runtime/reference/node_apis.md, runtime/reference/ts_config_migration.md
Two kinds of grammar fixes in this PR:
- `generateNodeCompatibility()` has been corrected, `...tability..` to `...tibility...`
- typos in markdown, in words
As always, don't hesitate to edit/change/cancel/request changes to this PR.
=> docs: fix typos

reference/_components/DocEntry.tsx, static/reference_styles.css
Before:
After:
Fixes: https://github.com/denoland/docs/issues/1503
=> move tags to after codeblock

_components/Breadcrumbs.tsx
Localhost: http://localhost:3000/runtime/reference/cli/bench/
Prod: https://docs.deno.com/runtime/reference/cli/bench/
Implementation is as per Lume maintainers' [recommendation](https://github.com/lumeland/lume/issues/739).
Previously, markdown in titles ended up in breadcrumb, with backticks visible on `<code>` pieces.
No more!
Feel free to edit, change, reject, close, take over — whatever is best for the project.
=> fix: render breadcrumbs last element as markdown

deploy/api/runtime-broadcast-channel.md, examples/tutorials/aws_lightsail.md, examples/tutorials/digital_ocean.md, examples/tutorials/google_cloud_run.md, examples/tutorials/prisma.md, examples/tutorials/word_finder.md
- `https://deno.land/x/hono/mod.ts` to `jsr:@hono/hono`
- `https://deno.land/x/oak/mod.ts` to `jsr:@oak/oak`
=> fix: replace imports deno.land to jsr

runtime/fundamentals/ffi.mdx
From https://github.com/NeKzor/docs-1/blob/main/runtime/reference/deno_namespace_apis.md#supported-types
=> docs(ffi): added information for flag numbers in FFI supported types

examples/tutorials/mocking.md, examples/tutorials/testing.md
shorten title
remove toc, doesn't actually improve usability
=> remove ToC from docs, it doesnt add to usability

examples/tutorials/aws_lambda.md, examples/videos/deploy_deno_to_aws_lambda.md
Tested both tutorials with updated adapter, works well
=> update lambda tutorial to use most recent aws adapter

runtime/reference/cli/serve.md
`request.url` is returning a full url: `http://localhost:3000/json`
`startsWith` wont match, but `endsWith` does
=> fix: deno serve example with json conditional

deploy/manual/postgres.md, examples/videos/deploying_deno_with_docker.md, runtime/fundamentals/workspaces.md, runtime/getting_started/setup_your_environment.md, runtime/reference/cli/publish.md, runtime/reference/cli/repl.md
A selection of small updates to docs addressing specific feedback and questions
- Describe default location of deno REPL history
- Describe LSP support for Zed
- Links to more onfo on using docker
- mention that deno.json exports can be string or object
- add description of what export property is for
- replace http import with JSR in this example
=> Feedback clarifications

runtime/contributing/index.md, runtime/reference/node_apis.md
We have started tracking the passing and failing Node.js test cases in [this page](https://node-test-viewer.deno.dev/results/latest). ref https://github.com/denoland/deno/issues/28318
This PR adds the reference to that page to ensure contributors are aware of it
=> Add reference to Node test result viewer

runtime/reference/cli/coverage.md
Since https://github.com/denoland/docs/pull/1121 was merged, there have been some changes to the `// deno-coverage-ignore*` comments, including the following:
- Removing the `-next` suffix for `// deno-coverage-ignore`
- Adding warnings for nested ignore ranges
- Adding warnings for unterminated ignore ranges
This PR updates the docs for `deno coverage` to match the latest behavior.
See https://github.com/denoland/deno/pull/26590
=> docs: Update coverage ignore docs

runtime/getting_started/setup_your_environment.md
Without `file-types` the LSP does not work with Deno 2.2.8 in Helix 25.01.1
=> Updates Helix languages.toml

runtime/reference/cli/coverage.md, runtime/reference/env_variables.md
This PR documents `DENO_COVERAGE_DIR` env var, implemented in https://github.com/denoland/deno/pull/28291
The feature will be shipped in Deno v2.3
=> Document DENO_COVERAGE_DIR env var

runtime/reference/cli/doc.md
- Align description of `typeparam` tag to TSDoc
I noticed today while browsing the ["Supported Tags" section of `deno doc`](https://docs.deno.com/runtime/reference/cli/doc/#supported-tags) docs that "define a callback" seems to have been copypasta'd into the `typeparam` tag.
I updated this to match the description from the linked TSDoc page.
=> Align typeparam description to TSDoc

deploy/kv/manual/cron.md
Currently the `Deno.cron` documentation for retrying failed runs ([Source](https://docs.deno.com/deploy/kv/manual/cron/#retrying-failed-runs)) shows a code snippet that is, I am assuming, out of date as it recommends setting the options object as the fourth parameter when in reality it should be the third parameter & the last parameter is always set to be the cron handler.
=> docs: Fix cron schedule backoff example

examples/scripts/duckdb.ts
People told me that DuckDB example is outdated and not working now, and I confirmed it is the case:
```sh
➜ deno run --allow-read --allow-write --allow-env --allow-net --allow-ffi https://docs.deno.com/examples/scripts/duckdb.ts
error: Uncaught (in promise) Error: Could not open library: Could not open library: libduckdb.so: cannot open shared object file: No such file or directory
return Deno.dlopen<S>(await download(options), symbols as any);
^
at new DynamicLibrary (ext:deno_ffi/00_ffi.js:456:42)
at Object.dlopen (ext:deno_ffi/00_ffi.js:562:10)
at dlopen (https://jsr.io/@divy/plug/1.0.3/mod.ts:155:15)
at eventLoopTick (ext:core/01_core.js:178:7)
at async https://jsr.io/@divy/duckdb/0.2.1/lib.js:41:27
```
Then, after some exploration, now the official Node-API binding library just works …
=> Update duckdb example

runtime/reference/cli/completions.md
On Fedora, bash completions live at `/usr/share/bash-completion/completions/`.
=> docs(completions): support other Linux distros

runtime/contributing/style_guide.md
We still prefer and are comfortable with this rule. I think we should keep this rule in the style guide.
=> Add back "Prefer top level function declaration" rule with some reasoning

deno.lock, runtime/reference/deno_namespace_apis.md, runtime/reference/web_platform_apis.md
Unfortunately, the Title and ToC plugins we're using do not work with mdx.  This means that any pages that are mdx files do not get the table of contents or the headings with anchor tags.
We will have to re-evaluate how we add more complicated components to the markdown. For now I have swapped the files back to .md files and just thrown some html in there to render the CTAs. 
I imagine the fix might be to make our own markdown-it plugins to render custom components.
=> move mdx files back to md

examples/videos/deno_fmt.md, examples/videos/interoperability_with_nodejs.md
This PR fixes several documentation issues:
1. Added the missing stdin indicator ("-") in the deno fmt pipe examples, which
is required when passing content through stdin.
2. Corrected the Node.js fs import syntax in the interoperability example to use
the proper default import pattern.
3. Fixed the escaped quotes example in the deno_fmt documentation to correctly
show the initial string with escaped quotes before formatting.
Special thanks to Johan Dahl for bringing these issues to our attention via
email.
=> fix examples for deno fmt and Node.js fs imports

deploy/manual/pricing-and-limits.md
Update to `/deploy/manual/pricing-and-limits/`
closes #1705
=> state that no upload request limits exist

runtime/fundamentals/configuration.md
Though some of the `patch` feature seems to be unstable (NPM patching), patching local dependencies looked stable to me. Writing this in the docs will allow developers to provide more feedback on it.
Related:
- https://github.com/denoland/deno/pull/25068
- https://github.com/denoland/deno/issues/25110
=> Add information about the `patch` field in `deno.json`

examples/tutorials/mocking.md
doctests failed because 
1. `FakeTime` is from `@std/testing/mock`
2. `fakeTime` does not exists
=> fix: nonexistent `fakeTime`

runtime/fundamentals/configuration.md
With Deno 2.3.6, the `patch` field has been renamed to `links`. This PR updates the docs.
- https://github.com/denoland/deno/pull/29677
P.S. I would be grateful if the PR that makes `links` work with Vite get reviewed too.
- https://github.com/denoland/deno-vite-plugin/pull/69
=> Introduce `links` instead of `patch` in `deno.json` docs

runtime/fundamentals/modules.md
Hey, noticed this while reading the docs, the github repo mentioned has been deprecated and the standard is now a part of the HTML standard, changed the url to that.
=> fix: change fundamentals/modules 'Import Maps Standard' link

_includes/renderCommand.tsx, replacements.json, runtime/reference/cli/_commands_reference.json
https://github.com/denoland/docs/pull/1848 is breaking because it doesn't expect null entries in the commands reference, this adds a check for null or empty values.
=> chore: update for 2.3.7 #1848

runtime/fundamentals/node.md
Closes https://github.com/denoland/docs/issues/724
Hopefully...
=> update info on buffer

examples/tutorials/express.md
| Before | After |
| :--: | :--: |
| <img width="674" height="614" alt="Screenshot 2025-07-14 at 19 07 59" src="https://github.com/user-attachments/assets/7a3d5892-b65a-4917-a9ac-a8c7168edd0a" /> | <img width="634" height="707" alt="Screenshot 2025-07-14 at 19 08 26" src="https://github.com/user-attachments/assets/4f191823-6bc3-445f-91ca-fee2ca2de483" /> |
=> fix(minor): remove typo in Express example

deploy/early-access/_data.ts, deploy/early-access/reference/button.md
Adds initial docs for the Deploy Button
`/deploy/early-access/reference/button/`
These will be expanded when support for cloning Playgrounds this way is added
closes #1883
=> Deploy Button docs

examples/tutorials/react.md
This pull request updates the instructions in the `examples/tutorials/react.md` file to correct the installation commands for configuring Vite and Deno together. The changes ensure the correct package names and versions are used.
* **Dependency installation fixes:**
* Updated the Vite plugin dependency from `npm:deno-vite-plugin` to `npm:@deno/vite-plugin` to reflect the correct package name.
* Removed unnecessary version placeholders (`@`) from the Oak dependency in the `deno add` command.
=> fix package install name typo in React Tutorial

_components/Logo.tsx, _includes/layout.tsx
Closes https://github.com/denoland/docs/issues/1912
Looks like there are a lot of reasons for the weird blip of loading unstyled content, including network, caching, (I think) Firefox itself, and loading so much CSS from so many different sources. But this reordering of the items in the `<head>` seems to help, at least.
=> Shuffle head links to reduce CLS

examples/videos/deno_fmt.md
There's a typo in the documentation of the fmt, when copying and pasting this text, it fails because it's semiColons with an 's' at the end.
=> fix typo on fmt json

_components/Hamburger.tsx, _components/Header.tsx, _components/TableOfContentsMobile.tsx, styles.css, tailwind.config.js
Mainly changes breakpoints from `px` units to `rem` units, so that responsive sizing scales with the user's font preference, not just the screen size. Also makes some other minor adjustments for better responsiveness, such as forcing `.markdown-body` to inherit font size, rather than set it at an inflexible `16px`.
=> Responsive fixes

examples/scripts/http_server_websocket.ts, runtime/fundamentals/http_server.md
426 is the proper error code for servers that expect websocket connections and do not recieve such
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/426
=> fix: use error code 426 upgrade required in websocket docs

_components/Navigation.tsx, _components/TableOfContents.tsx, _components/TableOfContentsItem.tsx, _includes/layout.tsx, reference/_components/DocEntry.tsx, static/reference_styles.css, styles.css
-  Makes the right and left sidebar symmetrical, in terms of width. Might look a little odd on some pages with very short ToC content, but I think it's an overall improvement, particularly above XL breakpoint. It also means navigating between docs pages is a little smoother, since the layout is always the same.
- Removes the scrollbar from the left sidebar. I did this because it looks better, and because I feel it's probably very intuitive that the left sidebar is scrollable (it's virtually always overflowing, and is common convention anyway), but this specific change I could be persuaded both ways. I know scrollbars should generally be visible always, but here I think there's very little reason for concern. (If we keep this: do we also do the same for the right sidebar?)
- Fixes some …
=> Symmetrical sidebars

_components/Footer.tsx, _components/Navigation.tsx, _components/TableOfContentsItem.tsx, styles.css
Let's update the footer to look more consistent with the sidebar (and also add a few missing items, and separate the docs into Deno/Services sections).
Also adds a utility class to the theme for the font-sizing of the sidebar and footer, since we're now using it in multiple places.
**Old:**
**New:**
=> Update footer links and styles

examples/tutorials/fetch_data.md
I noticed "bite stream" was used instead of "byte stream", so I decided to open a PR to make the change :)
=> Fixed typo (examples/tutorials/fetch_data.md) - changed "bite" to "byte"

runtime/fundamentals/open_telemetry.md
=> Update open_telemetry.md JS API docs links

orama/generate_orama_index_full.ts, reference/reference.page.tsx, reference_gen/common.ts, search.client.ts
point site at new datasource in orama, because old one does not seem to be uploading
=> fix broken urls at source rather than in the indexer

examples/tutorials/prisma.md
Page https://docs.deno.com/examples/prisma_tutorial/ has section "Let's understand the key parameters", where arguments description written on Portugal instead of English
this PR translates it to English
=> fix: translate Portugal to English

runtime/fundamentals/configuration.md
This pull request fixes a small mistake in the example of the permissions section. Neither the schema nor deno 2.5.0 allows a `string` to be passed to "read". It only allows a `boolean`, `string[]`, or `{ allow?: boolean | string[], deny?: boolean | string[] }`.
=> fix: An example `deno.json` file

examples/videos/publishing_modules_with_jsr.md
Feedback suggested that the publish to jsr link was not obvious enough, have added a big yellow button
closes #2546 
Old: 
New:
=> make a prominent publish to jsr button, closes #2546

runtime/fundamentals/workspaces.md
closes #1247 
> [Workspaces](https://docs.deno.com/runtime/fundamentals/workspaces/) can have multiple workspace members. Currently this is not something we mention in the documentation.
=> updating info on workspaces

styles.css
Ensures that when linking directly to a specific heading, the page doesn't scroll too far and hide the heading behind the nav.
=> Adjust anchor scrolltop on Services pages

examples/tutorials/vue.md
In [Vue.js tutorial page](https://docs.deno.com/examples/vue_tutorial/) inside the "deploy your own" section, it has "SvelteKit" written instead of "Vue.js"
=> Fix framework typo on Vue.js Tutorial
